### ISSUE TITLE
Do you need to have windows 10 sdk installed to use this?

### ISSUE THREAD

**Issue by erik-ciq** [spatools/node-signtool#1]
It's unclear to me from the documentation if I need to have the windows 10 sdk which provides SignTool.exe installed, or if it's packaged as part of this project. It looks like windows 10 sdk needs to be installed, please confirm.

**Comment by SomaticIT** [comment]
Hello,

You do not need any software to use this package.
In fact, you could also use it on linux by installing `wine`.

Thanks
